name: CI Pipeline

on:
  push:
    branches:
    - main

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Start Server
        working-directory: ./server
        run: npm start

  build-client:
    runs-on: ubuntu-latest
    needs: build-server

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Build Client
        working-directory: ./client
        run: npm run build
